"""Evidence-led case content. Historical facts and present-day proposals stay separate."""
from html import escape
from components import flow, summary, source

ONTO = 'https://github.com/tecnomod-um/OntoGenix/blob/3c1693b6f1292920b479027fe889af9861d99555/'
BIO = 'https://github.com/mikelval82/Biosignals/blob/821d3dd2d48c16bedf5e10f8cbbdc74d1a04f85a/'
EVAL = 'https://github.com/tecnomod-um/OntoGenixEvaluation#results-of-the-estimation-of-time-saving'

ontology_flow = flow('OntoGenix main data flow', [
    ('Profile the data', 'CSV → column statistics in JSON'),
    ('PlanSage', 'Task + data profile → schema and external links'),
    ('OntoBuilder', 'Data profile + planner output → Turtle ontology'),
    ('OntoMapper', 'Ontology + CSV reference → RML mapping'),
    ('KGen', 'Mapping + CSV → RDF graph in N-Triples')
], 'Main path reconstructed from the public source. Ontology parsing can feed errors back to OntoBuilder. Mapping can alternatively start from the planner output.',
    '<strong>Coordination:</strong> Genie selects actions using the current state and possible transitions. The application holds the intermediate results.')

context_rows = [
    ('PromptCrafter', 'User request + JSON data profile', 'Refined task instructions; optional step'),
    ('PlanSage', 'Task + JSON profile + optional metadata', 'Schema proposal, followed by an interoperability response'),
    ('OntoBuilder', 'JSON profile + current planner response', 'Turtle ontology; error feedback on a retry'),
    ('OntoMapper', 'Ontology or planner response, CSV path and format example', 'RML mapping; available execution feedback'),
    ('Genie', 'Request + current state + possible next states', 'Action selection and transition request'),
]
context_table = '<div class="table-scroll" role="region" aria-label="Agent context contracts" tabindex="0"><table><caption>What each agent receives and produces</caption><thead><tr><th scope="col">Component</th><th scope="col">Input context</th><th scope="col">Output</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<{tag}{attr}>{escape(x)}</{tag}>' for tag,attr,x in [('th',' scope="row"',a),('td','',b),('td','',c)])+'</tr>' for a,b,c in context_rows)+'</tbody></table></div>'

results = [('Airlines',41.8),('Amazon',48.5),('BigBasket',29.7),('Brazilian e-commerce',33.1),('Customer complaints',8.2),('E-commerce',58.3)]
result_chart = '<figure class="result-chart"><div class="figure-heading">Time saved in the team study <span>% versus modelling from scratch</span></div>'+''.join(f'<div class="result-row"><span>{label}</span><div class="result-track" aria-hidden="true"><span style="width:{value}%"></span></div><strong>{value}%</strong></div>' for label,value in results)+f'<figcaption>Includes generation, human review and adaptation. Excludes CSV analysis common to both workflows. <a href="{EVAL}">Protocol and source data ↗</a></figcaption></figure>'

TECHNICAL_CASES = [
dict(path='blog-ontogenix.html', title='OntoGenix', eyebrow='01 / Agentic AI & knowledge engineering',
 deck='Decomposing ontology engineering into specialised agents, with explicit context at each step.',
 meta='Universidad de Murcia · 2023–2024 · Published 2025', art='graph',
 role='Concept, architecture, implementation and manuscript writing. Validation carried out by other research team members.',
 cover=summary([('My contribution','From initial idea to implemented system and manuscript'),('Core decision','Specialised tasks, explicit context and intermediate artifacts'),('Evidence','Public implementation, saved examples and a team evaluation')]),
 sections=[
 ('overview','The problem behind the architecture', '''<p>Ontology engineering turns a dataset into an explicit model of its meaning: classes, properties and relationships that other systems can use. It combines interpretation, formal modelling and data transformation.</p><p>During development, asking agents to perform several complex steps led to hallucinations and errors. I designed specialised roles to narrow each task and the context it needed.</p><div class="callout"><p><strong>My contribution:</strong> I developed the concept, designed and implemented the system, and wrote the manuscript. Other members of the research team carried out the validation.</p></div>'''),
 ('architecture','The system, from input to graph', ontology_flow + '<p>The controller assembles inputs from application state and previous outputs. The shared LLM client sends a system role and a task-specific message; it does not automatically append the full conversation history to those text calls.</p><p>That makes the information crossing each boundary explicit. Keeping it complete and up to date becomes an engineering responsibility.</p><p class="source-note">'+source('GUI/GuiManager/GuiBehavior.py#L221','Controller and agent setup',ONTO)+' · '+source('GUI/LLM_base/LlmBase.py#L87','LLM request construction',ONTO)+'</p>'+context_table),
 ('decisions','Two decisions that shaped the system', '''<div class="decision"><p class="eyebrow">Decision 01</p><h3>Separate interpretation from formalisation</h3><p>PlanSage works on the intended model; OntoBuilder expresses it in Turtle; OntoMapper connects it to source data. This addressed the errors I observed when too many complex steps were combined.</p><p><strong>Trade-off:</strong> smaller tasks create more boundaries. Names, relationships and constraints must survive the handoff. Specialisation does not, by itself, establish semantic correctness.</p></div><div class="decision"><p class="eyebrow">Decision 02</p><h3>Check generated artifacts with executable tools</h3><p>The ontology path attempts RDF parsing and sends syntax feedback, including the problematic output, into a bounded retry loop. The generation entry point allows up to four attempts.</p><p><strong>Trade-off:</strong> a valid Turtle document can still model the domain incorrectly. Syntax checking supports the workflow; expert evaluation answers a different question.</p></div><p class="source-note">'''+source('GUI/GuiManager/GuiBehavior.py#L451','Ontology retry loop',ONTO)+' · '+source('GUI/OntologyManager/OntologyManager.py#L60','RDF parsing',ONTO)+'</p>'),
 ('example','Follow one stored example', '''<p>The Amazon Ratings example makes the intermediate representations visible. Its saved prompt asks for a model around orders, customers and articles. The schema names those concepts, the ontology expresses them, and the mapping connects them to CSV columns.</p><ol class="artifact-list"><li><strong>Intent → schema</strong><span>SalesOrder, Customer and SalesArticle; relationships such as hasCustomer.</span>'''+source('datasets/AmazonRating/crafted/schema.txt','Inspect the saved schema',ONTO)+'''</li><li><strong>Schema → ontology</strong><span>Classes and properties represented in Turtle.</span>'''+source('datasets/AmazonRating/crafted/ontology_LLM.ttl','Inspect the ontology',ONTO)+'''</li><li><strong>Ontology → mapping</strong><span>UserId, ProductId and Rating connected to graph resources and properties.</span>'''+source('datasets/AmazonRating/crafted/Chunk_ratings_Beauty_rml_mapping_LLM.csv.ttl','Inspect the RML mapping',ONTO)+'''</li></ol><p class="source-note">These are stored research artifacts, not a newly reproduced run or a claim that every output is correct.</p>'''),
 ('evaluation','Results, with their conditions', '<p>The team compared generated and human-developed ontologies across six commercial datasets. The assisted workflow saved time in every case, while the qualitative assessment generally favoured human modelling. Generated ontologies were richer in annotations but retained modelling errors.</p>'+result_chart+'<p>The study used expert review, OQuaRE and OOPS! Its results concern the complete assisted workflow; they do not isolate the effect of agent specialisation. I did not conduct this validation.</p>'),
 ('reflection','What I would improve today', '''<p>I would preserve the data profile, schema and external alignments as separate, versioned artifacts. In the inspected code, the interoperability call replaces PlanSage’s answer, which OntoBuilder then consumes. That creates a risk of losing part of the original schema.</p><p>I would also replace fragile text delimiters with validated structured outputs. For mappings, I would make the retry policy explicit: the inspected controller accepts feedback, but its automatic retry loop is commented out.</p><p class="source-note">These are present-day observations from source inspection, not newly reproduced runtime failures.</p><ul class="resource-list"><li>'''+source('GUI/PlanSage/LLM_planner.py#L100','Inspect context updates',ONTO)+'''<span>The boundary between schema creation and interoperability.</span></li><li><a href="https://doi.org/10.1016/j.ipm.2024.104042">Read the research paper ↗</a><span>Val-Calvo, M., et al. · Information Processing &amp; Management, 62(3), 104042.</span></li><li><a href="https://github.com/tecnomod-um/OntoGenixEvaluation">Explore the team evaluation ↗</a><span>Methods, datasets, results and limitations.</span></li></ul><p class="source-note">Code reference: <code>3c1693b</code>. Source and prompts inspected; the application and scientific experiments have not been rerun for this portfolio.</p>''')],
 next=('project-asisvia.html','ASISVIA')),

dict(path='project-asisvia.html', title='ASISVIA', eyebrow='02 / Generative AI & human interaction',
 deck='Conceiving a generative AI system for managing patient interviews and analysing their results.',
 meta='MindFrameAI · LabLENI / Contribution during 2024–2025', art='voice',
 role='Conception of the generative AI system for interview management and analysis of results.',
 cover=summary([('My contribution','System conception and high-level design'),('Design focus','Connect the interview with the analysis of its results'),('Project context','Patient experience · ASISVIA / PAIS-20241015')]),
 sections=[
 ('overview','From a conversation to useful information', '''<p>ASISVIA explores virtual agents and voice interaction for collecting and analysing patient experience. The project is led by Hospitales Universitarios San Roque in collaboration with research partners including UPV / LabLENI.</p><p><strong>My contribution was the conception of a generative AI system for managing interviews and analysing their results.</strong> It brings together my work on agent-based systems and my research background in human behaviour.</p><p class="source-note"><a href="https://hospitalessanroque.com/es/transparencia">Official project description ↗</a></p>'''),
 ('concept','The concept I worked on', flow('Conceptual interview and analysis flow',[
     ('Interview objective','Topics and information to collect'),('Generative interaction','Manage the interview conversation'),('Interview record','Preserve responses for interpretation'),('Analysis','Turn responses into interpretable results')
 ], 'Conceptual reconstruction of the interview-and-analysis scope. It illustrates design intent, not an implementation diagram or a recorded session.')+'''<p>The important connection is between what an interview asks and what its analysis can legitimately conclude. Both need to serve the same information goal.</p>'''),
 ('reasoning','The architectural questions', '''<div class="decision"><p class="eyebrow">Interaction</p><h3>Where should the conversation adapt?</h3><p>A generative interview can follow up on a response. The design question is how to preserve the interview’s purpose while allowing that flexibility: which topics must be covered, what can vary and when the interaction should end.</p></div><div class="decision"><p class="eyebrow">Analysis</p><h3>How does a result stay connected to its source?</h3><p>The analysis should distinguish what a participant said from the interpretation of that response. A useful design review asks which interview evidence supports a result, and what uncertainty needs to remain visible.</p></div><p>These questions explain the system-level reasoning behind the concept. Specific session-management mechanisms, model providers and deployment choices are outside the implementation evidence presented here.</p>'''),
 ('scope','Contribution and project scope', '''<p>The public project description covers satisfaction analysis, emotional-state research, virtual reality and user management. My account here focuses on the generative interview and results-analysis concept.</p><p>This case presents conceptual work and high-level design. It does not claim that I implemented every module, delivered a production deployment or validated clinical outcomes.</p><div class="callout"><p><strong>What this case demonstrates:</strong> framing a generative AI application around an interaction and its downstream information needs, within a multidisciplinary research project.</p></div><ul class="resource-list"><li><a href="https://hospitalessanroque.com/es/transparencia">ASISVIA: official project context ↗</a><span>Purpose, partners and module descriptions.</span></li><li><a href="https://lableni.webs.upv.es/cbr/">MindFrameAI research context ↗</a><span>Agents, cognition and human interaction.</span></li><li><a href="blog-ontogenix.html">See my implementation work: OntoGenix ↗</a><span>Architecture decisions connected to public source code.</span></li></ul>''')],
 next=('blog-biosignals.html','BIOSIGNALS')),

dict(path='blog-biosignals.html', title='BIOSIGNALS', eyebrow='03 / Experimental research software',
 deck='Keeping physiological signals and experimental events together, from acquisition to analysis.',
 meta='Open-source research software · Python / PyQt5', art='signal',
 role='Software author: physiological acquisition, visualisation and experimental recording workflows.',
 cover=summary([('My contribution','Research software design and development'),('Engineering focus','Signal acquisition, event markers and recording state'),('Evidence','Public source, documented trigger protocol and application screenshot')]),
 sections=[
 ('overview','Signals need experimental context', '''<p>A physiological trace becomes more useful when it can be related to what happened during an experiment. BIOSIGNALS brings live acquisition, visualisation and event labels into the same workflow.</p><p>I developed the software for experiments using BVP, GSR, temperature and accelerometer signals.</p><figure><img src="images/blog/BIOSIGNALS.png" alt="BIOSIGNALS research interface with physiological traces, recording controls and event labels" loading="lazy" width="1200"><figcaption>The research application. Historical screenshot from the project.</figcaption></figure>'''),
 ('architecture','Acquisition and experiment control', flow('BIOSIGNALS acquisition and event flow',[
     ('Acquire','Physiological streams from the device interface'),('Buffer & display','Channel data managers and live traces'),('Label','Experiment events attached to the recording'),('Store','Signal data and markers for offline analysis')
 ], 'Conceptual flow based on the application and data-manager source. Timing precision depends on the hardware and execution environment.', '<strong>Experiment control:</strong> a separate TCP/IP trigger interface carries recording commands and event labels.')+'''<p>The trigger interface lets an experiment communicate with the recorder without driving the GUI. The application handles the recording state, while data managers buffer channels and store annotations.</p><p><strong>Trade-off:</strong> separating those components makes integration possible, but timing and state transitions need validation under the actual acquisition conditions.</p>'''),
 ('example','A small protocol with a useful boundary', '''<div class="protocol"><span>start</span><span aria-hidden="true">→</span><span>event label</span><span aria-hidden="true">→</span><span>stop</span></div><p>The repository documents start and stop commands plus asynchronous event labels. In the inspected data manager, an annotation time is calculated from the sample index and configured sampling rate, then stored with the signal data.</p><p class="source-note">'''+source('DATA_MANAGERS/data_manager_02.py','Sample-based annotations and stored data',BIO)+'''</p><p>The repository includes an EDF writer, while the inspected data-manager variant stores NumPy files containing data, sampling information and triggers. Recording format therefore depends on the version and entry point.</p>'''),
 ('evidence','Source, use and limits', '''<p>This is experimental research software. The screenshot and source make the workflow inspectable; they do not establish a measured latency or synchronisation guarantee. The current checkout was reviewed without connecting acquisition hardware or running an experiment.</p><p>A useful next validation would compare event timestamps against an external reference while testing recording start, stop and reconnect behaviour.</p><ul class="resource-list"><li>'''+source('BIOSIGNALS_APP_01.py#L68','Recording state and trigger handling',BIO)+'''<span>How experiment events reach the data managers.</span></li><li>'''+source('EDF/writeEDFFile.py','EDF export component',BIO)+'''<span>An alternative recording component included in the repository.</span></li><li><a href="https://github.com/mikelval82/Biosignals">Source and documented usage ↗</a><span>Code reference: 821d3dd. Hardware and dependencies are required.</span></li><li><a href="https://doi.org/10.5281/zenodo.3759262">Software citation ↗</a><span>Persistent reference for the research software.</span></li><li><a href="https://doi.org/10.1142/S0129065720500136">Related research: multimodal emotion estimation ↗</a><span>International Journal of Neural Systems, 2020.</span></li></ul>''')],
 next=('project-biotechnology.html','Biotechnology & neuroengineering')),
]
